# Generated by Django 3.2.12 on 2022-04-18 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('everyName', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestid', models.IntegerField()),
                ('checkin', models.DateTimeField()),
                ('chekout', models.DateTimeField()),
                ('iscreated', models.DateField()),
                ('isupdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofguest', models.IntegerField()),
                ('totalprice', models.CharField(max_length=255)),
                ('purposeDescribe', models.CharField(max_length=255)),
                ('ReservationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.reservation')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
