# Generated by Django 3.2.12 on 2022-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='media/')),
                ('is_verified', models.BooleanField()),
                ('auth_provided', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
